baseURL: "https://ppsantos.github.io/" 
title: Pedro P. Santos
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        #- name: Books
        #  url: books/
        #  weight: 1 
        - name: Posts
          url: posts/
          weight: 2
        #- name: Courses
        #  url: courses/
        #  weight: 3
        #- name: Data
        #  url: data/
        #  weight: 4 
        #- name: Blog
        #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 5

params:
    description: "I am a PhD student in Computer Science and Engineering at Instituto Superior Técnico, University of Lisbon, and an early stage researcher at GAIPS, INESC-ID. I am supervised by Prof. Francisco S. Melo and Prof. Alberto Sardinha. My research addresses problems in decision-making and machine learning, particularly in planning and learning under uncertainty. I am particularly interested in the theoretical foundations of sequential decision-making. I got my MSc degree in Computer Science and Engineering from Instituto Superior Técnico in 2021."
    author: Pedro P. Santos
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pedro P. Santos
          subtitle: "I am a PhD student in Computer Science and Engineering at Instituto Superior Técnico, University of Lisbon, and an early stage researcher at GAIPS, INESC-ID. I am supervised by Prof. Francisco S. Melo and Prof. Alberto Sardinha. My research addresses problems in decision-making and machine learning, particularly in planning and learning under uncertainty. I am particularly interested in the theoretical foundations of sequential decision-making. I got my MSc degree in Computer Science and Engineering from Instituto Superior Técnico in 2021."
          imageUrl: "tagus_edited_darktable.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Pedro P. Santos
          buttons:
            - name: Contact me
              url: contacts/
            - name: Posts
              url: posts/
            - name: Articles
              url: https://scholar.google.com/citations?user=mJWH9dEAAAAJ
            #- name: Courses
            #  url: courses/
            #- name: Data
            #  url: data/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: Email
          url: mailto:pedro.pinto.santos@tecnico.ulisboa.pt
        #- name: CV
        #  url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=mJWH9dEAAAAJ
        #- name: Contacts
        #  url: contacts/
        #- name: Office Hours
        #  url: officehours/
        - name: GitHub
          url: https://github.com/PPSantos
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://twitter.com/ppspedrosantos

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Pedro P. Santos"
      icon: favicon.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2